import Head from 'next/head'
export default function HeadContainer () {
    return(
        <Head>
        <title>ZLATOMAX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    )
}